grab/urls.py
from django.conf.urls import patterns, include, url

from .views import IndexView, InfoView, CreateView, DeleteView

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^info/$', InfoView.as_view(), name='info'),
    url(r'^create/$', CreateView.as_view(), name='create'),
    url(r'^delete/$', DeleteView.as_view(), name='delete'),
)

grab_project/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'grab_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'', include('grab.urls', namespace='grab')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grab/models.py
# coding: utf-8

from django.db import models

# Create your models here.

class Link(models.Model):
    id = models.CharField(max_length=64, primary_key=True)
    url = models.CharField(max_length=1000)
    title = models.CharField(max_length=1000, blank=True, null=True)
    h1 = models.CharField(max_length=1000, blank=True, null=True)
    img = models.ImageField(upload_to='uploads/%Y/%m/%d/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s (%s)' % (self.url, self.id)

grab/forms.py
# coding: utf-8

from django import forms
from django.forms import formsets
from django.utils.translation import ugettext_lazy as _


class LinkForm(forms.Form):
    url = forms.CharField(max_length=1000, label=_('Url to grab'), widget=forms.TextInput(attrs={'class':'form-control'}))

LinkFormset = formsets.formset_factory(LinkForm, extra=1, max_num=5)

grab/views.py
# coding: utf-8

import json
import datetime
from celery import states

from django.core.paginator import Paginator
from django.conf import settings
from django.http.response import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic import View, TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from grab_project import celery_app
from .tasks import parse_url
from .forms import LinkFormset
from .models import Link

# Create your views here.

class IndexView(TemplateView):
    
    template_name = 'grab/index.html'

    def get_context_data(self, *kwargs):
        links = self.request.session.get('links', [])
        context = super(IndexView, self).get_context_data(*kwargs)
        paginator = Paginator(Link.objects.filter(id__in=links).order_by('-created'), settings.GRAB_PER_PAGE)

        context['formset'] = LinkFormset
        context['paginator'] = paginator

        return context

    def get(self, request):
        if request.is_ajax():
            page = request.GET.get('page', 1)
            paginator = self.get_context_data().get('paginator')
            return JsonResponse({'data': render_to_string('grab/_links.html', {'links': paginator.page(page)})})
        return super(IndexView, self).get(request)


class CreateView(View):

    def post(self, request):
        links = request.session.get('links', [])

        formset = LinkFormset(request.POST)
        countdown = request.POST.get('countdown', 0)
        if countdown:
            countdown = (datetime.datetime.strptime(countdown, '%m/%d/%Y %I:%M %p') - datetime.datetime.now()).total_seconds()
        if formset.is_valid():
            for form in formset[::-1]:
                if form.is_valid():
                    url = form.cleaned_data.get('url')
                    if url:
                        task = parse_url.apply_async((url,), countdown=countdown)
                        link = Link.objects.create(id=task.id, url=url)
                        links.append(link.id)
                else:                      
                    pass
        
        paginator = Paginator(links, settings.GRAB_PER_PAGE)
        request.session['links'] = links
        return JsonResponse({'success': True, 'num_pages': paginator.num_pages })


class DeleteView(View):

    def post(self, request, *args, **kwargw):
        task_id = request.POST.get('task_id')
        task = celery_app.AsyncResult(task_id)
        task.revoke(terminate=True)
        return JsonResponse({'success': True})

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(DeleteView, self).dispatch(*args, **kwargs)


class InfoView(View):

    def post(self, request, *args, **kwargs):
        result = []
        for task_id in request.POST.values():
            task = celery_app.AsyncResult(task_id)
            state = task.state
            cls = 'progress-bar-info'
            info = ''
            if state == states.SUCCESS:
                percent = 100
                link = Link.objects.get(pk=task_id)
                info = render_to_string('grab/_link_info.html', {'link': link})
            elif state == states.FAILURE:
                percent = 100
                cls = 'progress-bar-danger'
            elif state == states.REVOKED:
                percent = 100
                cls = 'progress-bar-warning'
            else:
                try: percent = task.info.get('percent', 0)
                except: percent = 0
            message = state
            result.append({'id': task_id, 'percent': percent, 'message': message, 'cls': cls, 'info':info})
        return JsonResponse({'data': result})
    
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(InfoView, self).dispatch(*args, **kwargs)

templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Grab</title>

        <!-- Bootstrap -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        {% block extra_css %}
        {% endblock extra_css %}
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'grab:home' %}">Grab project</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">                                                                                                    '
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            {% block content %}
            {% endblock content %}
        </div><!-- /.container -->

        {% block modals %}
        {% endblock modals %}

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static 'vendor/jquery/jquery-3.1.1.min.js' %}"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        {% block extra_js %}
        {% endblock extra_js %}
    </body>
</html>

templates/grab/_link.html
{% load i18n %}

{% trans 'Url' %}: {{ link.url }}
<div class="row">
    <div class="col-xs-11">
        <div class="progress" data-toggle="collapse" data-target="#id-info-{{ link.id }}">
            <div id="id-{{ link.id }}" class="progress-bar {% if cls %}{{ cls }}{% else %}progress-bar-info{% endif %}" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                {{ link.id }}
            </div>
        </div>
    </div>
    <div class="col-xs">
        <button class="btn btn-default delete-btn" type="button" onclick="$('#id-confirm-delete').attr('task_id', '{{ link.id }}').attr('url', '{{ link.url }}').modal('show');">
            <span class="fa fa-trash-o"></span>
        </button>
    </div>
</div>
{% include 'grab/_link_info.html' with link=link %}

templates/grab/_link_info.html
{% load i18n %}

<div id="id-info-{{ link.id }}" class="row collapse link-info" {% if link.img %}style="background-image: url({{ link.img.url }}); background-repeat: no-repeat;"{% endif %}>
    {% if link.title %}
    <div class="row">
        <div class="col-xs-2">{% trans 'title' %}</div>
        <div class="col-xs-10">{{ link.title }}</div>
    </div>
    {% endif %}
    {% if link.h1 %}
    <div class="row">
        <div class="col-xs-2">{% trans 'H1' %}</div>
        <div class="col-xs-10">{{ link.h1 }}</div>
    </div>
    {% endif %}
</div>

templates/grab/_links.html
{% for link in links %}
    {% include 'grab/_link.html' with link=link %}
{% endfor %}

templates/grab/index.html
{% include 'base.html' %}

{% load i18n %}
{% load staticfiles %}


{% block content %}
    <div id="id-create-links" class="container">                                                     
        <h1>
            {% trans "Please" %}, 
            <button id="id-add-link" type="button" class="btn btn-lg btn-success" onClick="javascript:void(0);">{% trans "add" %}</button> 
            {% trans "links and press" %}
            <button id="id-start" type="button" class="btn btn-lg btn-primary">{% trans 'start' %}</button>
        </h1>
        <div class="row">
            <div class="col-xs-8">{% trans 'There is possibility to delay start, if You wish, just fill this' %}</div>
            <div class="col-xs-4">
                <div class='input-group date' id='id-delay'>
                    <input name="countdown" id="id-countdown" type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="fa fa-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <form id="id-link-form" method="post" action="">
            {% csrf_token %}
            {% for form in formset.forms %}
            <div id="{{ form.prefix }}-row" class="form-row">
                <div class="input-group">
                    {{ form.url }} 
                    <span class="input-group-btn">
                        <button class="btn btn-default delete-btn" type="button" onClick="javascript:void(0);">
                            <span class="fa fa-trash-o"></span>
                        </button>
                    </span>
                </div>
            </div>
            {% endfor %}
            {{ formset.management_form }}
        </form>
    </div>
    <div class="container page">
        {% include 'grab/_links.html' %}
    </div>
    <div class="container text-center">
        <nav aria-label="Page navigation">
            <ul class="pagination" id="id-pagination"></ul>
        </nav>
    </div>
{% endblock content %}

{% block modals %}
<div id="id-confirm-delete" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">{% trans 'Delete task?' %}</h4>
            </div>
            <div class="modal-body">
                <p>{% trans 'Are you sure want to delete this task?' %}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'No' %}</button>
                <button type="button" id="id-delete-task" class="btn btn-danger">{% trans 'Delete' %}</button>
            </div>
        </div>

    </div>
</div>
{% endblock modals %}


{% block extra_css %}
    <link href="{% static 'vendor/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
{% endblock extra_css %}


{% block extra_js %}
    <script src="{% static 'vendor/jquery/jquery.formset.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/moment/moment.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/twbs-pagination/jquery.twbsPagination.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/js-cookie/js.cookie.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        function addLink() {
            var add_button = $(this).closest('.container').find('.add-row'); 
            if ($('#id-link-form .form-row').length < {{ formset.max_num }}) { 
                add_button.trigger('click'); 
            } 
            return false;
        }

        function deleteLink() {
            $(this).closest('.input-group').next('.delete-row').trigger('click'); 
            return false;
        }

        function deleteTask() {
            var dialog = $('#id-confirm-delete');
            $.post(
                "{% url 'grab:delete' %}", 
                {task_id: dialog.attr('task_id')},
                function (data) {
                    dialog.modal('hide');
                }
            )
        }

        function showPage(page) {
            Cookies.set('last-active-page', page);
            $.get(
                '{% url "grab:home" %}',
                {page: page},
                function (data) {
                    $('.page').html(data['data']);
                }
            )
        }

        var defaultOpts = {
            initiateStartPageClick: true,
            visiblePages: 5,
            onPageClick: function (event, page) {
                showPage(page)
            }
        };

        function start() {                                
            $.post(
                '{% url "grab:create" %}',
                $('#id-link-form').serialize() + '&' + $.param({'countdown': $('#id-countdown').val()}),
                function (data) {
                    if (data.success) {
                        var pagination = $('#id-pagination');
                        var totalPages = data.num_pages;
                        var currentPage = pagination.twbsPagination('getCurrentPage');
                        pagination.twbsPagination('destroy');
                        pagination.twbsPagination($.extend({}, defaultOpts, {
                            startPage: currentPage,
                            totalPages: totalPages,
                        }));
                        $('.delete-row').trigger('click');
                    }
                }
            )
            return false;
        }

        function getUncompleteIds() {
            ids = {};
            $('.progress-bar').each(function (index, value) {
                var style = $(this).attr('style');
                if (!style || style.indexOf('100%') == -1) {
                    ids[index] = $(value).attr('id').replace('id-', '');
                }
            })
            return ids;
        }

        function getInfo() {
            var ids = getUncompleteIds();
            if (!$.isEmptyObject(ids)) {
                $.post(
                    '{% url "grab:info" %}',
                    ids, 
                    function (data) {
                        $(data['data']).each(function (index, value) {
                            $('#id-'+value.id).css('width', value.percent+'%').text(value.message+' ({% trans "click for details..." %})').addClass(value.cls)
                            if (value.info) {
                                $('#id-info-'+value.id).replaceWith($(value.info));
                            }
                        })
                    },
                    'json'
                )
            }
        }

        $(document).ready(function () {
            $('#id-pagination').twbsPagination($.extend({}, defaultOpts, {
                startPage: parseInt(Cookies.get('last-active-page')) || 1,
                totalPages: {{ paginator.num_pages }},
            }));

            $('form div.form-row').formset({
                deleteCssClass: 'delete-row hide',
                addCssClass: 'add-row hide',
                added: function (row) {
                    $(row).find('.delete-btn').bind('click', deleteLink);
                }
            });
            $('#id-delay').datetimepicker();
            $('#id-add-link').bind('click', addLink);
            $('#id-start').bind('click', start);
            $('.delete-btn').bind('click', deleteLink);
            $('#id-confirm-delete').on('shown.bs.modal', function () {
                $(this).find('.modal-body').text("{% trans 'Are you sure want to delete this task' %} "+$(this).attr('url')+'?');
            });
            $('#id-delete-task').bind('click', deleteTask);

            setInterval(getInfo, 500); 
        })
    </script>

{% endblock extra_js %}